add button sollution
js-tasks-ru/htmlcss-20211021_vortexnz21 pull request #3
Opened 2022-01-02 23:02 UTC by grinvlad

2022-01-02 23:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-05 22:17 UTC, GSemikozov requested changes

2022-01-05 22:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: background 200ms ease-in-out, border 200ms ease-in-out;
транзишн можно указывать сразу на .button, отработает при. любом изменении состояния указанных свойств

2022-01-05 22:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
еще на disabled принято добавлять pointer-events: none чтобы пользователь не мог взаимодействовать с таким элементом

2022-01-05 22:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled {
в кнопках разных типов при disabled на самом деле фон менять не надо, достаточно opacity

2022-01-06 12:40 UTC, grinvlad commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
Круто. Сначала не понял, почему будет лучше не менять background при disabled (т.к. при наведении мышью кнопка продолжала подсвечиваться как активная), а c pointer-events: none; это починилось

2022-01-06 13:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-06 18:02 UTC, merged