add main-index solution after 1 lesson
js-tasks-ru/htmlcss-20211021_vortexnz21 pull request #5
Opened 2022-01-16 15:51 UTC by grinvlad

1. Сомневаюсь в выборе серого border'а вокруг основной области, решил отнести к preview.
2. Сомневаюсь в идее модификатора content_footer к блоку content. Я вначале второй лекции подслушал, что добавив класс content, мы отошли от БЭМ к Atomic CSS. Уместен ли в таком случае модификатор к нему?

2022-01-16 15:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-18 20:12 UTC, GSemikozov requested changes

2022-01-18 20:12 UTC, GSemikozov commented on components/footer/footer.css
> +.container_footer {
это модификатор контейнера, его там и надо определять. Но - полагаю, хотелось оформить именно элемент футера) можно просто элемент .footer__text-container

2022-01-18 20:12 UTC, GSemikozov commented on components/preview/preview.css
> +    border-top: 1px solid var(--grey-2);
это скорее часть хедера

2022-01-18 20:12 UTC, GSemikozov commented on components/preview/preview.css
> +    border-bottom: 1px solid var(--grey-2);
а это часть футера

2022-01-20 15:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-20 19:22 UTC, GSemikozov requested changes

2022-01-20 19:22 UTC, GSemikozov commented on components/preview/preview.css
> +    border-top: 1px solid var(--grey-2);
из preview соответственно надо удалить)

2022-01-21 19:02 UTC, GSemikozov approved these changes

2022-01-21 19:02 UTC, merged