Add skeleton solution
js-tasks-ru/htmlcss-20211021_vortexnz21 pull request #6
Opened 2022-01-20 16:04 UTC by grinvlad

2022-01-20 19:25 UTC, GSemikozov requested changes

2022-01-20 19:25 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
ширину и высоту не стоит жестко фиксировать, это плохо скажется на адаптивности

2022-01-20 19:25 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.line-1 {
все модификаторы желательно задать в процентах (опять же для адаптивности) + класс-модификатор в начале должен содержать тот блок/элемент к которому применяется, в нашем случае это например .skeleton__line_line-1. Но и самим модификаторам лучше дать более информативные имена (отвечают на вопрос что делает / что или как модифицирует, например .skeleton__line_short)

2022-01-20 19:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-20 22:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-21 19:03 UTC, GSemikozov approved these changes

2022-01-21 19:03 UTC, merged